<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	array(
		'id' => 'sy-list-12',
		'name' => 'Duft Nr. 12',
		'name_en' => 'Fragrance No. 12',
		'name_ar' => 'عطر رقم 12',
		'beschreibung' => 'Ein sinnlicher Duft mit fruchtiger Süße, würziger Wärme und edler Tiefe.',
		'beschreibung_en' => 'A sensual fragrance with fruity sweetness, spicy warmth, and refined depth.',
		'beschreibung_ar' => 'عطر حسي يجمع بين حلاوة فاكهية ودفء حار وعمق راقٍ.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'holzig',
			'gourmand',
		),
		'duftnoten' => array(
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'gewuerznoten',
			'suesse_gourmand',
		),
		'produktlink' => 'https://alowidat.de/product/12/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/12.png',
		'priority_order' => 1,
	),
	array(
		'id' => 'sy-list-152',
		'name' => 'Duft Nr. 152',
		'name_en' => 'Fragrance No. 152',
		'name_ar' => 'عطر رقم 152',
		'beschreibung' => 'Florale Eleganz verschmilzt mit sinnlicher Wärme und zeitloser Anmut.',
		'beschreibung_en' => 'Floral elegance melts into sensual warmth and timeless grace.',
		'beschreibung_ar' => 'أناقة زهرية تذوب في دفء حسي ونعومة خالدة.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'blumig',
		),
		'duftnoten' => array(
			'blumige_noten',
		),
		'produktlink' => 'https://alowidat.de/product/152/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/152.png',
		'priority_order' => 2,
	),
	array(
		'id' => 'sy-list-179',
		'name' => 'Duft Nr. 179',
		'name_en' => 'Fragrance No. 179',
		'name_ar' => 'عطر رقم 179',
		'beschreibung' => 'Fruchtige Süße trifft auf romantische Eleganz und sinnliche Wärme.',
		'beschreibung_en' => 'Fruity sweetness meets romantic elegance and sensual warmth.',
		'beschreibung_ar' => 'حلاوة فاكهية تلتقي بأناقة رومانسية ودفء حسي.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'10_20',
			'20_30',
		),
		'duftrichtungen' => array(
			'blumig',
			'fruchtig',
		),
		'duftnoten' => array(
			'blumige_noten',
			'fruchtige_noten',
			'suesse_gourmand',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/179/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/179.png',
		'priority_order' => 3,
	),
	array(
		'id' => 'sy-list-18',
		'name' => 'Duft Nr. 18',
		'name_en' => 'Fragrance No. 18',
		'name_ar' => 'عطر رقم 18',
		'beschreibung' => 'Pudrige Eleganz verbindet sich mit holziger Tiefe und zeitloser Raffinesse.',
		'beschreibung_en' => 'Powdery elegance blends with woody depth and timeless refinement.',
		'beschreibung_ar' => 'أناقة بودرية تمتزج مع عمق خشبي ورقي خالد.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'holzig',
		),
		'duftnoten' => array(
			'blumige_noten',
			'holznoten',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/18/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/18-700x700.webp',
		'priority_order' => 4,
	),
	array(
		'id' => 'sy-list-180',
		'name' => 'Duft Nr. 180',
		'name_en' => 'Fragrance No. 180',
		'name_ar' => 'عطر رقم 180',
		'beschreibung' => 'Süße Verführung verbindet sich mit floraler Eleganz und warmer Tiefe.',
		'beschreibung_en' => 'Sweet seduction blends with floral elegance and warm depth.',
		'beschreibung_ar' => 'إغراء حلو يمتزج مع أناقة زهرية وعمق دافئ.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'10_20',
			'20_30',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'gourmand',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'holznoten',
			'suesse_gourmand',
			'erdige_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/180/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/180.png',
		'priority_order' => 5,
	),
	array(
		'id' => 'sy-list-21',
		'name' => 'Duft Nr. 21',
		'name_en' => 'Fragrance No. 21',
		'name_ar' => 'عطر رقم 21',
		'beschreibung' => 'Würzige Wärme trifft auf sinnliche Tiefe und zeitlose Eleganz.',
		'beschreibung_en' => 'Spicy warmth meets sensual depth and timeless elegance.',
		'beschreibung_ar' => 'دفء حار يلتقي بعمق حسي وأناقة خالدة.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'wuerzig',
			'holzig',
			'amber',
			'gourmand',
		),
		'duftnoten' => array(
			'holznoten',
			'gewuerznoten',
			'harze_balsame',
			'suesse_gourmand',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/21/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2026/03/21.webp',
		'priority_order' => 6,
	),
	array(
		'id' => 'sy-list-253',
		'name' => 'Duft Nr. 253',
		'name_en' => 'Fragrance No. 253',
		'name_ar' => 'عطر رقم 253',
		'beschreibung' => 'Süße Wärme trifft auf florale Sinnlichkeit und moderne Eleganz.',
		'beschreibung_en' => 'Sweet warmth meets floral sensuality and modern elegance.',
		'beschreibung_ar' => 'دفء حلو يلتقي بحسية زهرية وأناقة عصرية.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'grosse_raeume',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'10_20',
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'gourmand',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'suesse_gourmand',
			'erdige_noten',
		),
		'produktlink' => 'https://alowidat.de/product/253/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/253.png',
		'priority_order' => 7,
	),
	array(
		'id' => 'sy-list-31',
		'name' => 'Duft Nr. 31',
		'name_en' => 'Fragrance No. 31',
		'name_ar' => 'عطر رقم 31',
		'beschreibung' => 'Fruchtige Frische verbindet sich mit kraftvoller Eleganz und zeitlosem Stil.',
		'beschreibung_en' => 'Fruity freshness blends with powerful elegance and timeless style.',
		'beschreibung_ar' => 'انتعاش فاكهي يمتزج مع أناقة قوية وأسلوب خالد.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'fruchtig',
			'holzig',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'erdige_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/31/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/31.png',
		'priority_order' => 8,
	),
	array(
		'id' => 'sy-list-321',
		'name' => 'Duft Nr. 321',
		'name_en' => 'Fragrance No. 321',
		'name_ar' => 'عطر رقم 321',
		'beschreibung' => 'Florale Leichtigkeit verbindet sich mit sanfter Frische und pudriger Eleganz.',
		'beschreibung_en' => 'Floral lightness blends with gentle freshness and powdery elegance.',
		'beschreibung_ar' => 'خفة زهرية تمتزج مع انتعاش ناعم وأناقة بودرية.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'10_20',
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'blumig',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/321/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/321.png',
		'priority_order' => 9,
	),
	array(
		'id' => 'sy-list-323',
		'name' => 'Duft Nr. 323',
		'name_en' => 'Fragrance No. 323',
		'name_ar' => 'عطر رقم 323',
		'beschreibung' => 'Fruchtige Frische verschmilzt mit floraler Eleganz und sanfter Tiefe.',
		'beschreibung_en' => 'Fruity freshness melts into floral elegance and gentle depth.',
		'beschreibung_ar' => 'انتعاش فاكهي يذوب في أناقة زهرية وعمق ناعم.',
		'geschlecht' => array(
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'20_30',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'fruchtig',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'erdige_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/323/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/323.png',
		'priority_order' => 10,
	),
	array(
		'id' => 'sy-list-337',
		'name' => 'Duft Nr. 337',
		'name_en' => 'Fragrance No. 337',
		'name_ar' => 'عطر رقم 337',
		'beschreibung' => 'Strahlende Frische trifft auf sinnliche Wärme und moderne Eleganz.',
		'beschreibung_en' => 'Radiant freshness meets sensual warmth and modern elegance.',
		'beschreibung_ar' => 'انتعاش مشرق يلتقي بدفء حسي وأناقة عصرية.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'10_20',
			'20_30',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'fruchtig',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'suesse_gourmand',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/337/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/337.png',
		'priority_order' => 11,
	),
	array(
		'id' => 'sy-list-341',
		'name' => 'Duft Nr. 341',
		'name_en' => 'Fragrance No. 341',
		'name_ar' => 'عطر رقم 341',
		'beschreibung' => 'Fruchtige Leichtigkeit verbindet sich mit floraler Eleganz und sanfter Sinnlichkeit.',
		'beschreibung_en' => 'Fruity lightness blends with floral elegance and gentle sensuality.',
		'beschreibung_ar' => 'خفة فاكهية تمتزج مع أناقة زهرية وحسية ناعمة.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'10_20',
			'20_30',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'fruchtig',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'suesse_gourmand',
			'erdige_noten',
		),
		'produktlink' => 'https://alowidat.de/product/341/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/341.png',
		'priority_order' => 12,
	),
	array(
		'id' => 'sy-list-353',
		'name' => 'Duft Nr. 353',
		'name_en' => 'Fragrance No. 353',
		'name_ar' => 'عطر رقم 353',
		'beschreibung' => 'Florale Eleganz trifft auf orientalische Tiefe und cremige Wärme.',
		'beschreibung_en' => 'Floral elegance meets oriental depth and creamy warmth.',
		'beschreibung_ar' => 'أناقة زهرية تلتقي بعمق شرقي ودفء كريمي.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'fruchtig',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'harze_balsame',
			'suesse_gourmand',
			'erdige_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/353/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/353.png',
		'priority_order' => 13,
	),
	array(
		'id' => 'sy-list-360',
		'name' => 'Duft Nr. 360',
		'name_en' => 'Fragrance No. 360',
		'name_ar' => 'عطر رقم 360',
		'beschreibung' => 'Reiner Moschus vereint sich mit floraler Weichheit und moderner Eleganz.',
		'beschreibung_en' => 'Pure musk unites with floral softness and modern elegance.',
		'beschreibung_ar' => 'مسك نقي يتحد مع نعومة زهرية وأناقة عصرية.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'10_20',
			'20_30',
		),
		'duftrichtungen' => array(
			'blumig',
			'moschus',
		),
		'duftnoten' => array(
			'blumige_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/360/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/360.png',
		'priority_order' => 14,
	),
	array(
		'id' => 'sy-list-362',
		'name' => 'Duft Nr. 362',
		'name_en' => 'Fragrance No. 362',
		'name_ar' => 'عطر رقم 362',
		'beschreibung' => 'Fruchtige Frische trifft auf süße Verführung und sinnliche Wärme.',
		'beschreibung_en' => 'Fruity freshness meets sweet seduction and sensual warmth.',
		'beschreibung_ar' => 'انتعاش فاكهي يلتقي بإغراء حلو ودفء حسي.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'10_20',
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'fruchtig',
			'gourmand',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'suesse_gourmand',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/362/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/362.png',
		'priority_order' => 15,
	),
	array(
		'id' => 'sy-list-380',
		'name' => 'Duft Nr. 380',
		'name_en' => 'Fragrance No. 380',
		'name_ar' => 'عطر رقم 380',
		'beschreibung' => 'Florale Sinnlichkeit verbindet sich mit honigsüßer Wärme und tiefer Eleganz.',
		'beschreibung_en' => 'Floral sensuality blends with honeyed warmth and deep elegance.',
		'beschreibung_ar' => 'حسية زهرية تمتزج مع دفء عسلي وأناقة عميقة.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'gourmand',
		),
		'duftnoten' => array(
			'blumige_noten',
			'harze_balsame',
			'suesse_gourmand',
			'erdige_noten',
		),
		'produktlink' => 'https://alowidat.de/product/380/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/380.png',
		'priority_order' => 16,
	),
	array(
		'id' => 'sy-list-384',
		'name' => 'Duft Nr. 384',
		'name_en' => 'Fragrance No. 384',
		'name_ar' => 'عطر رقم 384',
		'beschreibung' => 'Sanfte Reinheit trifft auf weichen Moschus und dezente Eleganz.',
		'beschreibung_en' => 'Gentle purity meets soft musk and subtle elegance.',
		'beschreibung_ar' => 'نقاء ناعم يلتقي بمسك ناعم وأناقة هادئة.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'10_20',
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'moschus',
		),
		'duftnoten' => array(
			'harze_balsame',
			'aromatische_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/384/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/384.png',
		'priority_order' => 17,
	),
	array(
		'id' => 'sy-list-389',
		'name' => 'Duft Nr. 389',
		'name_en' => 'Fragrance No. 389',
		'name_ar' => 'عطر رقم 389',
		'beschreibung' => 'Fruchtige Lebensfreude vereint sich mit floraler Leichtigkeit und warmer Eleganz.',
		'beschreibung_en' => 'Fruity joie de vivre unites with floral lightness and warm elegance.',
		'beschreibung_ar' => 'بهجة فاكهية تتحد مع خفة زهرية وأناقة دافئة.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'10_20',
			'20_30',
		),
		'duftrichtungen' => array(
			'blumig',
			'fruchtig',
			'moschus',
		),
		'duftnoten' => array(
			'blumige_noten',
			'fruchtige_noten',
			'suesse_gourmand',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/389/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/389.png',
		'priority_order' => 18,
	),
	array(
		'id' => 'sy-list-404',
		'name' => 'Duft Nr. 404',
		'name_en' => 'Fragrance No. 404',
		'name_ar' => 'عطر رقم 404',
		'beschreibung' => 'Fruchtige Frische verschmilzt mit sonniger Wärme und mediterraner Leichtigkeit.',
		'beschreibung_en' => 'Fruity freshness melts into sunny warmth and Mediterranean lightness.',
		'beschreibung_ar' => 'انتعاش فاكهي يذوب في دفء مشمس وخفة متوسطية.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'10_20',
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'fruchtig',
			'gourmand',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'fruchtige_noten',
			'suesse_gourmand',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/404/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/404.png',
		'priority_order' => 19,
	),
	array(
		'id' => 'sy-list-416',
		'name' => 'Duft Nr. 416',
		'name_en' => 'Fragrance No. 416',
		'name_ar' => 'عطر رقم 416',
		'beschreibung' => 'Leuchtende Eleganz vereint sich mit warmer Tiefe und zeitloser Raffinesse.',
		'beschreibung_en' => 'Luminous elegance unites with warm depth and timeless refinement.',
		'beschreibung_ar' => 'أناقة مضيئة تتحد مع عمق دافئ ورقي خالد.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'holzig',
			'amber',
		),
		'duftnoten' => array(
			'blumige_noten',
			'holznoten',
			'gewuerznoten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/416/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/416.png',
		'priority_order' => 20,
	),
	array(
		'id' => 'sy-list-427',
		'name' => 'Duft Nr. 427',
		'name_en' => 'Fragrance No. 427',
		'name_ar' => 'عطر رقم 427',
		'beschreibung' => 'Frische Klarheit verbindet sich mit floraler Eleganz und ruhiger Stärke.',
		'beschreibung_en' => 'Fresh clarity blends with floral elegance and calm strength.',
		'beschreibung_ar' => 'صفاء منعش يمتزج مع أناقة زهرية وقوة هادئة.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'buero',
			'meeting',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'gruen',
			'holzig',
		),
		'duftnoten' => array(
			'blumige_noten',
			'holznoten',
			'gewuerznoten',
			'erdige_noten',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/427/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/427.webp',
		'priority_order' => 21,
	),
	array(
		'id' => 'sy-list-43',
		'name' => 'Duft Nr. 43',
		'name_en' => 'Fragrance No. 43',
		'name_ar' => 'عطر رقم 43',
		'beschreibung' => 'Frische Energie trifft auf holzige Dynamik und elegante Tiefe.',
		'beschreibung_en' => 'Fresh energy meets woody dynamism and elegant depth.',
		'beschreibung_ar' => 'طاقة منعشة تلتقي بديناميكية خشبية وعمق أنيق.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'meeting',
			'date',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'holzig',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'holznoten',
			'erdige_noten',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/43/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/11/43.webp',
		'priority_order' => 22,
	),
	array(
		'id' => 'sy-list-437',
		'name' => 'Duft Nr. 437',
		'name_en' => 'Fragrance No. 437',
		'name_ar' => 'عطر رقم 437',
		'beschreibung' => 'Frische Eleganz verschmilzt mit cremiger Wärme und charismatischer Tiefe.',
		'beschreibung_en' => 'Fresh elegance melts into creamy warmth and charismatic depth.',
		'beschreibung_ar' => 'أناقة منعشة تذوب في دفء كريمي وعمق كاريزمي.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'buero',
			'meeting',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'fruchtig',
			'wuerzig',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'gewuerznoten',
			'suesse_gourmand',
			'erdige_noten',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/437/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/437.png',
		'priority_order' => 23,
	),
	array(
		'id' => 'sy-list-441',
		'name' => 'Duft Nr. 441',
		'name_en' => 'Fragrance No. 441',
		'name_ar' => 'عطر رقم 441',
		'beschreibung' => 'Strahlende Frische verbindet sich mit pudriger Eleganz und warmer Tiefe.',
		'beschreibung_en' => 'Radiant freshness blends with powdery elegance and warm depth.',
		'beschreibung_ar' => 'انتعاش مشرق يمتزج مع أناقة بودرية وعمق دافئ.',
		'geschlecht' => array(
			'herren',
			'unisex',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'meeting',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'fruchtig',
		),
		'duftnoten' => array(
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'suesse_gourmand',
			'erdige_noten',
		),
		'produktlink' => 'https://alowidat.de/product/441/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/441.png',
		'priority_order' => 24,
	),
	array(
		'id' => 'sy-list-487',
		'name' => 'Duft Nr. 487',
		'name_en' => 'Fragrance No. 487',
		'name_ar' => 'عطر رقم 487',
		'beschreibung' => 'Süße Verführung trifft auf dunkle Sinnlichkeit und warme Tiefe.',
		'beschreibung_en' => 'Sweet seduction meets dark sensuality and warm depth.',
		'beschreibung_ar' => 'إغراء حلو يلتقي بحسية داكنة وعمق دافئ.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'fruchtig',
			'gourmand',
		),
		'duftnoten' => array(
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'suesse_gourmand',
		),
		'produktlink' => 'https://alowidat.de/product/487/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/487.png',
		'priority_order' => 25,
	),
	array(
		'id' => 'sy-list-497',
		'name' => 'Duft Nr. 497',
		'name_en' => 'Fragrance No. 497',
		'name_ar' => 'عطر رقم 497',
		'beschreibung' => 'Frische Klarheit vereint sich mit würziger Eleganz und warmer Tiefe.',
		'beschreibung_en' => 'Fresh clarity unites with spicy elegance and warm depth.',
		'beschreibung_ar' => 'صفاء منعش يتحد مع أناقة حارة وعمق دافئ.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'wuerzig',
			'ledrig',
			'moschus',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'gewuerznoten',
			'harze_balsame',
			'suesse_gourmand',
			'aromatische_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/497/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/497.png',
		'priority_order' => 26,
	),
	array(
		'id' => 'sy-list-506',
		'name' => 'Duft Nr. 506',
		'name_en' => 'Fragrance No. 506',
		'name_ar' => 'عطر رقم 506',
		'beschreibung' => 'Edle Frische verschmilzt mit luxuriöser Wärme und majestätischer Tiefe.',
		'beschreibung_en' => 'Noble freshness melts into luxurious warmth and majestic depth.',
		'beschreibung_ar' => 'انتعاش فاخر يذوب في دفء مترف وعمق مهيب.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'winter',
		),
		'verwendungsbereich' => array(
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'oud',
			'holzig',
			'gourmand',
			'ledrig',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'holznoten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/506/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/506.png',
		'priority_order' => 27,
	),
	array(
		'id' => 'sy-list-515',
		'name' => 'Duft Nr. 515',
		'name_en' => 'Fragrance No. 515',
		'name_ar' => 'عطر رقم 515',
		'beschreibung' => 'Fruchtige Leichtigkeit verbindet sich mit sanfter Wärme und zeitloser Eleganz.',
		'beschreibung_en' => 'Fruity lightness blends with gentle warmth and timeless elegance.',
		'beschreibung_ar' => 'خفة فاكهية تمتزج مع دفء ناعم وأناقة خالدة.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'fruchtig',
			'moschus',
		),
		'duftnoten' => array(
			'blumige_noten',
			'fruchtige_noten',
			'erdige_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/515/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/515.png',
		'priority_order' => 28,
	),
	array(
		'id' => 'sy-list-516',
		'name' => 'Duft Nr. 516',
		'name_en' => 'Fragrance No. 516',
		'name_ar' => 'عطر رقم 516',
		'beschreibung' => 'Mediterrane Frische verschmilzt mit süßer Wärme und majestätischer Sinnlichkeit.',
		'beschreibung_en' => 'Mediterranean freshness melts into sweet warmth and majestic sensuality.',
		'beschreibung_ar' => 'انتعاش متوسطي يذوب في دفء حلو وحسية مهيبة.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
		),
		'duftrichtungen' => array(
			'wuerzig',
			'holzig',
			'amber',
		),
		'duftnoten' => array(
			'holznoten',
			'gewuerznoten',
			'harze_balsame',
			'suesse_gourmand',
			'erdige_noten',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/516/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/516.png',
		'priority_order' => 29,
	),
	array(
		'id' => 'sy-list-523',
		'name' => 'Duft Nr. 523',
		'name_en' => 'Fragrance No. 523',
		'name_ar' => 'عطر رقم 523',
		'beschreibung' => 'Orientalische Wärme verbindet sich mit königlicher Eleganz und luxuriöser Tiefe.',
		'beschreibung_en' => 'Oriental warmth blends with royal elegance and luxurious depth.',
		'beschreibung_ar' => 'دفء شرقي يمتزج مع أناقة ملكية وعمق فاخر.',
		'geschlecht' => array(
			'herren',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'fruchtig',
			'oud',
			'holzig',
			'amber',
		),
		'duftnoten' => array(
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'gewuerznoten',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/523/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/523.png',
		'priority_order' => 30,
	),
	array(
		'id' => 'sy-list-534',
		'name' => 'Duft Nr. 534',
		'name_en' => 'Fragrance No. 534',
		'name_ar' => 'عطر رقم 534',
		'beschreibung' => 'Leuchtende Frische vereint sich mit inspirierender Wärme und moderner Eleganz.',
		'beschreibung_en' => 'Luminous freshness unites with inspiring warmth and modern elegance.',
		'beschreibung_ar' => 'انتعاش مضيء يتحد مع دفء ملهم وأناقة عصرية.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'fruchtig',
			'aquatisch',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'holznoten',
			'gewuerznoten',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/534/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/534.png',
		'priority_order' => 31,
	),
	array(
		'id' => 'sy-list-54',
		'name' => 'Duft Nr. 54',
		'name_en' => 'Fragrance No. 54',
		'name_ar' => 'عطر رقم 54',
		'beschreibung' => 'Würzige Frische verschmilzt mit süßer Wärme und charismatischer Ausstrahlung.',
		'beschreibung_en' => 'Spicy freshness melts into sweet warmth and charismatic appeal.',
		'beschreibung_ar' => 'انتعاش حار يذوب في دفء حلو وجاذبية كاريزمية.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'wuerzig',
			'gourmand',
		),
		'duftnoten' => array(
			'gewuerznoten',
			'suesse_gourmand',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/54/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/54.png',
		'priority_order' => 32,
	),
	array(
		'id' => 'sy-list-544',
		'name' => 'Duft Nr. 544',
		'name_en' => 'Fragrance No. 544',
		'name_ar' => 'عطر رقم 544',
		'beschreibung' => 'Orientalische Opulenz trifft auf sinnliche Wärme und luxuriöse Tiefe.',
		'beschreibung_en' => 'Oriental opulence meets sensual warmth and luxurious depth.',
		'beschreibung_ar' => 'فخامة شرقية تلتقي بدفء حسي وعمق فاخر.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'oud',
			'wuerzig',
			'amber',
			'moschus',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'gewuerznoten',
			'suesse_gourmand',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/544/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/544.png',
		'priority_order' => 33,
	),
	array(
		'id' => 'sy-list-577',
		'name' => 'Duft Nr. 577',
		'name_en' => 'Fragrance No. 577',
		'name_ar' => 'عطر رقم 577',
		'beschreibung' => 'Frische Leichtigkeit verschmilzt mit cremiger Wärme und emotionaler Tiefe.',
		'beschreibung_en' => 'Fresh lightness melts into creamy warmth and emotional depth.',
		'beschreibung_ar' => 'خفة منعشة تذوب في دفء كريمي وعمق عاطفي.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'wuerzig',
			'gourmand',
			'moschus',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'gewuerznoten',
			'suesse_gourmand',
			'erdige_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/577/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/577.png',
		'priority_order' => 34,
	),
	array(
		'id' => 'sy-list-588',
		'name' => 'Duft Nr. 588',
		'name_en' => 'Fragrance No. 588',
		'name_ar' => 'عطر رقم 588',
		'beschreibung' => 'Fruchtige Frische trifft auf elegante Wärme und charismatische Ausstrahlung.',
		'beschreibung_en' => 'Fruity freshness meets elegant warmth and charismatic appeal.',
		'beschreibung_ar' => 'انتعاش فاكهي يلتقي بدفء أنيق وجاذبية كاريزمية.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'fruchtig',
			'holzig',
			'amber',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'gewuerznoten',
			'suesse_gourmand',
			'erdige_noten',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/588/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/588.png',
		'priority_order' => 35,
	),
	array(
		'id' => 'sy-list-595',
		'name' => 'Duft Nr. 595',
		'name_en' => 'Fragrance No. 595',
		'name_ar' => 'عطر رقم 595',
		'beschreibung' => 'Zitrische Frische verbindet sich mit warmer Eleganz und zeitloser Tiefe.',
		'beschreibung_en' => 'Citrus freshness blends with warm elegance and timeless depth.',
		'beschreibung_ar' => 'انتعاش حمضي يمتزج مع أناقة دافئة وعمق خالد.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'10_20',
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'fruchtig',
			'holzig',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'holznoten',
			'suesse_gourmand',
		),
		'produktlink' => 'https://alowidat.de/product/595/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/595.png',
		'priority_order' => 36,
	),
	array(
		'id' => 'sy-list-601',
		'name' => 'Duft Nr. 601',
		'name_en' => 'Fragrance No. 601',
		'name_ar' => 'عطر رقم 601',
		'beschreibung' => 'Würzige Wärme verschmilzt mit süßer Verführung und charismatischer Tiefe.',
		'beschreibung_en' => 'Spicy warmth melts into sweet seduction and charismatic depth.',
		'beschreibung_ar' => 'دفء حار يذوب في إغراء حلو وعمق كاريزمي.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'meeting',
			'date',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'10_20',
			'20_30',
		),
		'duftrichtungen' => array(
			'wuerzig',
			'gourmand',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'gewuerznoten',
			'suesse_gourmand',
		),
		'produktlink' => 'https://alowidat.de/product/601/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/601.png',
		'priority_order' => 37,
	),
	array(
		'id' => 'sy-list-606',
		'name' => 'Duft Nr. 606',
		'name_en' => 'Fragrance No. 606',
		'name_ar' => 'عطر رقم 606',
		'beschreibung' => 'Dunkle Wärme verbindet sich mit würziger Sinnlichkeit und verführerischer Tiefe.',
		'beschreibung_en' => 'Dark warmth blends with spicy sensuality and seductive depth.',
		'beschreibung_ar' => 'دفء داكن يمتزج مع حسية حارة وعمق مغرٍ.',
		'geschlecht' => array(
			'herren',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'wuerzig',
			'holzig',
			'gourmand',
		),
		'duftnoten' => array(
			'blumige_noten',
			'holznoten',
			'gewuerznoten',
			'suesse_gourmand',
		),
		'produktlink' => 'https://alowidat.de/product/606/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/606.png',
		'priority_order' => 38,
	),
	array(
		'id' => 'sy-list-608',
		'name' => 'Duft Nr. 608',
		'name_en' => 'Fragrance No. 608',
		'name_ar' => 'عطر رقم 608',
		'beschreibung' => 'Sanfte Wärme vereint sich mit cremiger Süße und harmonischer Eleganz.',
		'beschreibung_en' => 'Gentle warmth unites with creamy sweetness and harmonious elegance.',
		'beschreibung_ar' => 'دفء ناعم يتحد مع حلاوة كريمية وأناقة متناغمة.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'wuerzig',
			'holzig',
			'amber',
			'gourmand',
		),
		'duftnoten' => array(
			'holznoten',
			'suesse_gourmand',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/608/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/608.png',
		'priority_order' => 39,
	),
	array(
		'id' => 'sy-list-61',
		'name' => 'Duft Nr. 61',
		'name_en' => 'Fragrance No. 61',
		'name_ar' => 'عطر رقم 61',
		'beschreibung' => 'Spritzige Frische trifft auf aromatische Eleganz und sinnliche Tiefe.',
		'beschreibung_en' => 'Sparkling freshness meets aromatic elegance and sensual depth.',
		'beschreibung_ar' => 'انتعاش فوّار يلتقي بأناقة عطرية وعمق حسي.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'aquatisch',
			'moschus',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'suesse_gourmand',
		),
		'produktlink' => 'https://alowidat.de/product/61/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/61.png',
		'priority_order' => 40,
	),
	array(
		'id' => 'sy-list-610',
		'name' => 'Duft Nr. 610',
		'name_en' => 'Fragrance No. 610',
		'name_ar' => 'عطر رقم 610',
		'beschreibung' => 'Frische Klarheit trifft auf würzige Wärme und sinnliche Tiefe.',
		'beschreibung_en' => 'Fresh clarity meets spicy warmth and sensual depth.',
		'beschreibung_ar' => 'صفاء منعش يلتقي بدفء حار وعمق حسي.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'10_20',
			'20_30',
		),
		'duftrichtungen' => array(
			'wuerzig',
			'gourmand',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'gewuerznoten',
			'harze_balsame',
			'suesse_gourmand',
			'erdige_noten',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/610/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/610.png',
		'priority_order' => 41,
	),
	array(
		'id' => 'sy-list-615',
		'name' => 'Duft Nr. 615',
		'name_en' => 'Fragrance No. 615',
		'name_ar' => 'عطر رقم 615',
		'beschreibung' => 'Fruchtige Eleganz verbindet sich mit warmer Sinnlichkeit und geheimnisvoller Tiefe.',
		'beschreibung_en' => 'Fruity elegance blends with warm sensuality and mysterious depth.',
		'beschreibung_ar' => 'أناقة فاكهية تمتزج مع حسية دافئة وعمق غامض.',
		'geschlecht' => array(
			'herren',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'buero',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'fruchtig',
			'oud',
			'holzig',
			'amber',
			'gourmand',
			'ledrig',
			'moschus',
		),
		'duftnoten' => array(
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'suesse_gourmand',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/615/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/615.png',
		'priority_order' => 42,
	),
	array(
		'id' => 'sy-list-624',
		'name' => 'Duft Nr. 624',
		'name_en' => 'Fragrance No. 624',
		'name_ar' => 'عطر رقم 624',
		'beschreibung' => 'Strahlende Frische verschmilzt mit floraler Wärme und eleganter Tiefe.',
		'beschreibung_en' => 'Radiant freshness melts into floral warmth and elegant depth.',
		'beschreibung_ar' => 'انتعاش مشرق يذوب في دفء زهري وعمق أنيق.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'holzig',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'holznoten',
			'erdige_noten',
		),
		'produktlink' => 'https://alowidat.de/product/624/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/624.png',
		'priority_order' => 43,
	),
	array(
		'id' => 'sy-list-628',
		'name' => 'Duft Nr. 628',
		'name_en' => 'Fragrance No. 628',
		'name_ar' => 'عطر رقم 628',
		'beschreibung' => 'Cremige Süße verbindet sich mit warmer Eleganz und strahlender Sinnlichkeit.',
		'beschreibung_en' => 'Creamy sweetness blends with warm elegance and radiant sensuality.',
		'beschreibung_ar' => 'حلاوة كريمية تمتزج مع أناقة دافئة وحسية مشرقة.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'date',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'wuerzig',
			'holzig',
			'amber',
			'gourmand',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'holznoten',
			'gewuerznoten',
			'harze_balsame',
			'suesse_gourmand',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/628/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/628.png',
		'priority_order' => 44,
	),
	array(
		'id' => 'sy-list-630',
		'name' => 'Duft Nr. 630',
		'name_en' => 'Fragrance No. 630',
		'name_ar' => 'عطر رقم 630',
		'beschreibung' => 'Orientalische Wärme verschmilzt mit gourmandiger Süße und luxuriöser Tiefe.',
		'beschreibung_en' => 'Oriental warmth melts into gourmand sweetness and luxurious depth.',
		'beschreibung_ar' => 'دفء شرقي يذوب في حلاوة غورماند وعمق فاخر.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'wuerzig',
			'gourmand',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'holznoten',
			'gewuerznoten',
			'harze_balsame',
			'suesse_gourmand',
		),
		'produktlink' => 'https://alowidat.de/product/630/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/630.png',
		'priority_order' => 45,
	),
	array(
		'id' => 'sy-list-633',
		'name' => 'Duft Nr. 633',
		'name_en' => 'Fragrance No. 633',
		'name_ar' => 'عطر رقم 633',
		'beschreibung' => 'Fruchtige Frische vereint sich mit aromatischer Leichtigkeit und sanfter Wärme.',
		'beschreibung_en' => 'Fruity freshness unites with aromatic lightness and gentle warmth.',
		'beschreibung_ar' => 'انتعاش فاكهي يتحد مع خفة عطرية ودفء ناعم.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'10_20',
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'fruchtig',
			'gruen',
			'gourmand',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'suesse_gourmand',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/633/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/633.png',
		'priority_order' => 46,
	),
	array(
		'id' => 'sy-list-634',
		'name' => 'Duft Nr. 634',
		'name_en' => 'Fragrance No. 634',
		'name_ar' => 'عطر رقم 634',
		'beschreibung' => 'Cremige Vanille verbindet sich mit sinnlicher Wärme und verführerischer Tiefe.',
		'beschreibung_en' => 'Creamy vanilla blends with sensual warmth and seductive depth.',
		'beschreibung_ar' => 'فانيلا كريمية تمتزج مع دفء حسي وعمق مغرٍ.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'holzig',
			'gourmand',
		),
		'duftnoten' => array(
			'blumige_noten',
			'holznoten',
			'suesse_gourmand',
			'aromatische_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/634/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/634.png',
		'priority_order' => 47,
	),
	array(
		'id' => 'sy-list-641',
		'name' => 'Duft Nr. 641',
		'name_en' => 'Fragrance No. 641',
		'name_ar' => 'عطر رقم 641',
		'beschreibung' => 'Gourmandige Süße verschmilzt mit floraler Wärme und verträumter Sinnlichkeit.',
		'beschreibung_en' => 'Gourmand sweetness melts into floral warmth and dreamy sensuality.',
		'beschreibung_ar' => 'حلاوة غورماند تذوب في دفء زهري وحسية حالمة.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'fruchtig',
			'wuerzig',
			'holzig',
			'gourmand',
			'moschus',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'gewuerznoten',
			'suesse_gourmand',
			'aromatische_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/641/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/641.png',
		'priority_order' => 48,
	),
	array(
		'id' => 'sy-list-647',
		'name' => 'Duft Nr. 647',
		'name_en' => 'Fragrance No. 647',
		'name_ar' => 'عطر رقم 647',
		'beschreibung' => 'Würzige Eleganz vereint sich mit cremiger Wärme und charismatischer Tiefe.',
		'beschreibung_en' => 'Spicy elegance unites with creamy warmth and charismatic depth.',
		'beschreibung_ar' => 'أناقة حارة تتحد مع دفء كريمي وعمق كاريزمي.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'meeting',
			'date',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'wuerzig',
			'holzig',
			'gourmand',
		),
		'duftnoten' => array(
			'holznoten',
			'gewuerznoten',
			'suesse_gourmand',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/647/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/647.png',
		'priority_order' => 49,
	),
	array(
		'id' => 'sy-list-652',
		'name' => 'Duft Nr. 652',
		'name_en' => 'Fragrance No. 652',
		'name_ar' => 'عطر رقم 652',
		'beschreibung' => 'Belebende Frische verbindet sich mit aromatischer Leichtigkeit und natürlicher Eleganz.',
		'beschreibung_en' => 'Invigorating freshness blends with aromatic lightness and natural elegance.',
		'beschreibung_ar' => 'انتعاش منشّط يمتزج مع خفة عطرية وأناقة طبيعية.',
		'geschlecht' => array(
			'herren',
			'unisex',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'10_20',
			'20_30',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'gruen',
			'aquatisch',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'aromatische_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/652/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/652.png',
		'priority_order' => 50,
	),
	array(
		'id' => 'sy-list-653',
		'name' => 'Duft Nr. 653',
		'name_en' => 'Fragrance No. 653',
		'name_ar' => 'عطر رقم 653',
		'beschreibung' => 'Exotische Frische verschmilzt mit cremiger Wärme und sonniger Sinnlichkeit.',
		'beschreibung_en' => 'Exotic freshness melts into creamy warmth and sunny sensuality.',
		'beschreibung_ar' => 'انتعاش استوائي يذوب في دفء كريمي وحسية مشمسة.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'10_20',
			'20_30',
		),
		'duftrichtungen' => array(
			'fruchtig',
			'gruen',
			'holzig',
			'gourmand',
		),
		'duftnoten' => array(
			'fruchtige_noten',
			'holznoten',
			'suesse_gourmand',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/653/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/653.webp',
		'priority_order' => 51,
	),
	array(
		'id' => 'sy-list-654',
		'name' => 'Duft Nr. 654',
		'name_en' => 'Fragrance No. 654',
		'name_ar' => 'عطر رقم 654',
		'beschreibung' => 'Strahlende Frische vereint sich mit floraler Eleganz und sanfter Wärme.',
		'beschreibung_en' => 'Radiant freshness unites with floral elegance and gentle warmth.',
		'beschreibung_ar' => 'انتعاش مشرق يتحد مع أناقة زهرية ودفء ناعم.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'fruchtig',
			'wuerzig',
			'gourmand',
			'moschus',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'holznoten',
			'gewuerznoten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/654/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/654.png',
		'priority_order' => 52,
	),
	array(
		'id' => 'sy-list-658',
		'name' => 'Duft Nr. 658',
		'name_en' => 'Fragrance No. 658',
		'name_ar' => 'عطر رقم 658',
		'beschreibung' => 'Fruchtige Frische verschmilzt mit moderner Eleganz und sanfter Sinnlichkeit.',
		'beschreibung_en' => 'Fruity freshness melts into modern elegance and gentle sensuality.',
		'beschreibung_ar' => 'انتعاش فاكهي يذوب في أناقة عصرية وحسية ناعمة.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'10_20',
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'fruchtig',
			'holzig',
			'gourmand',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
		),
		'produktlink' => 'https://alowidat.de/product/658/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/658.png',
		'priority_order' => 53,
	),
	array(
		'id' => 'sy-list-659',
		'name' => 'Duft Nr. 659',
		'name_en' => 'Fragrance No. 659',
		'name_ar' => 'عطر رقم 659',
		'beschreibung' => 'Strahlende Frische verbindet sich mit floraler Weichheit und seidiger Eleganz.',
		'beschreibung_en' => 'Radiant freshness blends with floral softness and silky elegance.',
		'beschreibung_ar' => 'انتعاش مشرق يمتزج مع نعومة زهرية وأناقة حريرية.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'fruchtig',
			'gourmand',
			'moschus',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/659/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/11/659.webp',
		'priority_order' => 54,
	),
	array(
		'id' => 'sy-list-674',
		'name' => 'Duft Nr. 674',
		'name_en' => 'Fragrance No. 674',
		'name_ar' => 'عطر رقم 674',
		'beschreibung' => 'Exotische Süße vereint sich mit orientalischer Wärme und verführerischer Tiefe.',
		'beschreibung_en' => 'Exotic sweetness unites with oriental warmth and seductive depth.',
		'beschreibung_ar' => 'حلاوة استوائية تتحد مع دفء شرقي وعمق مغرٍ.',
		'geschlecht' => array(
			'herren',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'date',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'fruchtig',
			'oud',
			'holzig',
			'gourmand',
			'ledrig',
		),
		'duftnoten' => array(
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'gewuerznoten',
			'harze_balsame',
			'suesse_gourmand',
			'erdige_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/674/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/674.png',
		'priority_order' => 55,
	),
	array(
		'id' => 'sy-list-683',
		'name' => 'Duft Nr. 683',
		'name_en' => 'Fragrance No. 683',
		'name_ar' => 'عطر رقم 683',
		'beschreibung' => 'Exotische Fruchtigkeit verschmilzt mit cremiger Wärme und sinnlicher Tiefe.',
		'beschreibung_en' => 'Exotic fruitiness melts into creamy warmth and sensual depth.',
		'beschreibung_ar' => 'فاكهية استوائية تذوب في دفء كريمي وعمق حسي.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'10_20',
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'fruchtig',
			'gourmand',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'gewuerznoten',
			'suesse_gourmand',
			'erdige_noten',
		),
		'produktlink' => 'https://alowidat.de/product/683/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/683.png',
		'priority_order' => 56,
	),
	array(
		'id' => 'sy-list-684',
		'name' => 'Duft Nr. 684',
		'name_en' => 'Fragrance No. 684',
		'name_ar' => 'عطر رقم 684',
		'beschreibung' => 'Würzige Wärme verschmilzt mit floraler Eleganz und sinnlicher Tiefe.',
		'beschreibung_en' => 'Spicy warmth melts into floral elegance and sensual depth.',
		'beschreibung_ar' => 'دفء حار يذوب في أناقة زهرية وعمق حسي.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'wuerzig',
			'gourmand',
		),
		'duftnoten' => array(
			'blumige_noten',
			'gewuerznoten',
			'harze_balsame',
			'suesse_gourmand',
			'erdige_noten',
		),
		'produktlink' => 'https://alowidat.de/product/684/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/684.png',
		'priority_order' => 57,
	),
	array(
		'id' => 'sy-list-687',
		'name' => 'Duft Nr. 687',
		'name_en' => 'Fragrance No. 687',
		'name_ar' => 'عطر رقم 687',
		'beschreibung' => 'Gourmandige Süße vereint sich mit würziger Wärme und luxuriöser Sinnlichkeit.',
		'beschreibung_en' => 'Gourmand sweetness unites with spicy warmth and luxurious sensuality.',
		'beschreibung_ar' => 'حلاوة غورماند تتحد مع دفء حار وحسية فاخرة.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'10_20',
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'fruchtig',
			'gourmand',
			'moschus',
		),
		'duftnoten' => array(
			'fruchtige_noten',
			'holznoten',
			'gewuerznoten',
			'harze_balsame',
			'suesse_gourmand',
			'erdige_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/687/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/687.png',
		'priority_order' => 58,
	),
	array(
		'id' => 'sy-list-691',
		'name' => 'Duft Nr. 691',
		'name_en' => 'Fragrance No. 691',
		'name_ar' => 'عطر رقم 691',
		'beschreibung' => 'Fruchtige Süße verschmilzt mit gourmandiger Wärme und eleganter Tiefe.',
		'beschreibung_en' => 'Fruity sweetness melts into gourmand warmth and elegant depth.',
		'beschreibung_ar' => 'حلاوة فاكهية تذوب في دفء غورماند وعمق أنيق.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'date',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'10_20',
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'fruchtig',
			'holzig',
			'gourmand',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'suesse_gourmand',
		),
		'produktlink' => 'https://alowidat.de/product/691/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/691.png',
		'priority_order' => 59,
	),
	array(
		'id' => 'sy-list-695',
		'name' => 'Duft Nr. 695',
		'name_en' => 'Fragrance No. 695',
		'name_ar' => 'عطر رقم 695',
		'beschreibung' => 'Florale Sinnlichkeit verbindet sich mit goldener Wärme und süßer Tiefe.',
		'beschreibung_en' => 'Floral sensuality blends with golden warmth and sweet depth.',
		'beschreibung_ar' => 'حسية زهرية تمتزج مع دفء ذهبي وعمق حلو.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'fruchtig',
			'wuerzig',
			'amber',
			'gourmand',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'fruchtige_noten',
			'holznoten',
			'gewuerznoten',
			'suesse_gourmand',
			'aromatische_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/695/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/695.png',
		'priority_order' => 60,
	),
	array(
		'id' => 'sy-list-697',
		'name' => 'Duft Nr. 697',
		'name_en' => 'Fragrance No. 697',
		'name_ar' => 'عطر رقم 697',
		'beschreibung' => 'Cremige Süße vereint sich mit sanfter Wärme und purer Eleganz.',
		'beschreibung_en' => 'Creamy sweetness unites with gentle warmth and pure elegance.',
		'beschreibung_ar' => 'حلاوة كريمية تتحد مع دفء ناعم وأناقة نقية.',
		'geschlecht' => array(
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'grosse_raeume',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'gourmand',
			'moschus',
		),
		'duftnoten' => array(
			'fruchtige_noten',
			'holznoten',
			'suesse_gourmand',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/697/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/697.png',
		'priority_order' => 61,
	),
	array(
		'id' => 'sy-list-702',
		'name' => 'Duft Nr. 702',
		'name_en' => 'Fragrance No. 702',
		'name_ar' => 'عطر رقم 702',
		'beschreibung' => 'Belebende Frische trifft auf aromatische Eleganz und sinnliche Tiefe.',
		'beschreibung_en' => 'Invigorating freshness meets aromatic elegance and sensual depth.',
		'beschreibung_ar' => 'انتعاش منشّط يلتقي بأناقة عطرية وعمق حسي.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'10_20',
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'holzig',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'holznoten',
			'erdige_noten',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/702/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/11/702.webp',
		'priority_order' => 62,
	),
	array(
		'id' => 'sy-list-707',
		'name' => 'Duft Nr. 707',
		'name_en' => 'Fragrance No. 707',
		'name_ar' => 'عطر رقم 707',
		'beschreibung' => 'Orientalische Opulenz verbindet sich mit rauchiger Tiefe und majestätischer Eleganz.',
		'beschreibung_en' => 'Oriental opulence blends with smoky depth and majestic elegance.',
		'beschreibung_ar' => 'فخامة شرقية تمتزج مع عمق دخاني وأناقة مهيبة.',
		'geschlecht' => array(
			'herren',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'oud',
			'wuerzig',
			'holzig',
			'amber',
			'moschus',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'holznoten',
			'gewuerznoten',
			'harze_balsame',
			'suesse_gourmand',
			'erdige_noten',
			'aromatische_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/707/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2026/03/707.webp',
		'priority_order' => 63,
	),
	array(
		'id' => 'sy-list-713',
		'name' => 'Duft Nr. 713',
		'name_en' => 'Fragrance No. 713',
		'name_ar' => 'عطر رقم 713',
		'beschreibung' => 'Rauchige Eleganz verbindet sich mit holziger Wärme und zeitloser Tiefe.',
		'beschreibung_en' => 'Smoky elegance blends with woody warmth and timeless depth.',
		'beschreibung_ar' => 'أناقة دخانية تمتزج مع دفء خشبي وعمق خالد.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'oud',
			'wuerzig',
			'holzig',
			'amber',
			'ledrig',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'holznoten',
			'gewuerznoten',
			'harze_balsame',
			'suesse_gourmand',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/713/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2026/03/713.webp',
		'priority_order' => 64,
	),
	array(
		'id' => 'sy-list-726',
		'name' => 'Duft Nr. 726',
		'name_en' => 'Fragrance No. 726',
		'name_ar' => 'عطر رقم 726',
		'beschreibung' => 'Exotische Fruchtigkeit verschmilzt mit tropischer Frische und cremiger Wärme.',
		'beschreibung_en' => 'Exotic fruitiness melts into tropical freshness and creamy warmth.',
		'beschreibung_ar' => 'فاكهية فريدة تذوب في انتعاش استوائي ودفء كريمي.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'buero',
			'grosse_raeume',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'10_20',
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'fruchtig',
			'amber',
			'gourmand',
			'aquatisch',
			'moschus',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/726/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2026/06/726.webp',
		'priority_order' => 65,
	),
	array(
		'id' => 'sy-list-727',
		'name' => 'Duft Nr. 727',
		'name_en' => 'Fragrance No. 727',
		'name_ar' => 'عطر رقم 727',
		'beschreibung' => 'Fruchtige Eleganz verschmilzt mit orientalischer Wärme und sinnlicher Tiefe.',
		'beschreibung_en' => 'Fruity elegance melts into oriental warmth and sensual depth.',
		'beschreibung_ar' => 'أناقة فاكهية تذوب في دفء شرقي وعمق حسي.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'fruchtig',
			'wuerzig',
			'holzig',
			'amber',
			'gourmand',
			'moschus',
		),
		'duftnoten' => array(
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'gewuerznoten',
			'suesse_gourmand',
			'erdige_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/727/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2026/06/727.webp',
		'priority_order' => 66,
	),
	array(
		'id' => 'sy-list-77',
		'name' => 'Duft Nr. 77',
		'name_en' => 'Fragrance No. 77',
		'name_ar' => 'عطر رقم 77',
		'beschreibung' => 'Fruchtige tropische Frische verschmilzt mit warmer Sinnlichkeit und orientalischer Tiefe.',
		'beschreibung_en' => 'Fruity tropical freshness melts into warm sensuality and oriental depth.',
		'beschreibung_ar' => 'انتعاش استوائي فاكهي يذوب في حسية دافئة وعمق شرقي.',
		'geschlecht' => array(
			'herren',
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'fruchtig',
			'oud',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'gewuerznoten',
			'suesse_gourmand',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/77/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/11/77.webp',
		'priority_order' => 67,
	),
	array(
		'id' => 'sy-list-79',
		'name' => 'Duft Nr. 79',
		'name_en' => 'Fragrance No. 79',
		'name_ar' => 'عطر رقم 79',
		'beschreibung' => 'Würzige Frische trifft auf cremige Wärme und elegante Tiefe.',
		'beschreibung_en' => 'Spicy freshness meets creamy warmth and elegant depth.',
		'beschreibung_ar' => 'انتعاش حار يلتقي بدفء كريمي وعمق أنيق.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'wuerzig',
			'holzig',
			'gourmand',
		),
		'duftnoten' => array(
			'holznoten',
			'gewuerznoten',
			'harze_balsame',
			'suesse_gourmand',
			'erdige_noten',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/79/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/11/79.webp',
		'priority_order' => 68,
	),
	array(
		'id' => 'sy-list-80',
		'name' => 'Duft Nr. 80',
		'name_en' => 'Fragrance No. 80',
		'name_ar' => 'عطر رقم 80',
		'beschreibung' => 'Fruchtige Frische vereint sich mit würziger Tiefe und sinnlicher Wärme.',
		'beschreibung_en' => 'Fruity freshness unites with spicy depth and sensual warmth.',
		'beschreibung_ar' => 'انتعاش فاكهي يتحد مع عمق حار ودفء حسي.',
		'geschlecht' => array(
			'herren',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
		),
		'verwendungsbereich' => array(
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'fruchtig',
			'gruen',
			'wuerzig',
			'amber',
			'gourmand',
			'ledrig',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'gewuerznoten',
			'harze_balsame',
			'suesse_gourmand',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/80/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/11/80.webp',
		'priority_order' => 69,
	),
	array(
		'id' => 'sy-list-803',
		'name' => 'Duft Nr. 803',
		'name_en' => 'Fragrance No. 803',
		'name_ar' => 'عطر رقم 803',
		'beschreibung' => 'Cremige Weichheit verschmilzt mit pudriger Eleganz und sinnlicher Wärme.',
		'beschreibung_en' => 'Creamy softness melts into powdery elegance and sensual warmth.',
		'beschreibung_ar' => 'نعومة كريمية تذوب في أناقة بودرية ودفء حسي.',
		'geschlecht' => array(
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'20_30',
		),
		'duftrichtungen' => array(
			'blumig',
			'gourmand',
		),
		'duftnoten' => array(
			'blumige_noten',
			'suesse_gourmand',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/803/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/803.png',
		'priority_order' => 70,
	),
	array(
		'id' => 'sy-list-806',
		'name' => 'Duft Nr. 806',
		'name_en' => 'Fragrance No. 806',
		'name_ar' => 'عطر رقم 806',
		'beschreibung' => 'Cremige Vanille verbindet sich mit würziger Wärme und eleganter Sinnlichkeit.',
		'beschreibung_en' => 'Creamy vanilla blends with spicy warmth and elegant sensuality.',
		'beschreibung_ar' => 'فانيلا كريمية تمتزج مع دفء حار وحسية أنيقة.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'wuerzig',
			'gourmand',
		),
		'duftnoten' => array(
			'gewuerznoten',
			'suesse_gourmand',
			'aromatische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/806/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/806.png',
		'priority_order' => 71,
	),
	array(
		'id' => 'sy-list-810',
		'name' => 'Duft Nr. 810',
		'name_en' => 'Fragrance No. 810',
		'name_ar' => 'عطر رقم 810',
		'beschreibung' => 'Cremige Süße vereint sich mit warmer Sinnlichkeit und samtiger Tiefe.',
		'beschreibung_en' => 'Creamy sweetness unites with warm sensuality and velvety depth.',
		'beschreibung_ar' => 'حلاوة كريمية تتحد مع حسية دافئة وعمق مخملي.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'winter',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'gourmand',
		),
		'duftnoten' => array(
			'blumige_noten',
			'holznoten',
			'suesse_gourmand',
			'erdige_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/810/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/810.png',
		'priority_order' => 72,
	),
	array(
		'id' => 'sy-list-818',
		'name' => 'Duft Nr. 818',
		'name_en' => 'Fragrance No. 818',
		'name_ar' => 'عطر رقم 818',
		'beschreibung' => 'Gourmandige Süße verschmilzt mit floraler Eleganz und luxuriöser Wärme.',
		'beschreibung_en' => 'Gourmand sweetness melts into floral elegance and luxurious warmth.',
		'beschreibung_ar' => 'حلاوة غورماند تذوب في أناقة زهرية ودفء فاخر.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'gourmand',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'suesse_gourmand',
			'erdige_noten',
			'aromatische_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/818/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/818.png',
		'priority_order' => 73,
	),
	array(
		'id' => 'sy-list-820',
		'name' => 'Duft Nr. 820',
		'name_en' => 'Fragrance No. 820',
		'name_ar' => 'عطر رقم 820',
		'beschreibung' => 'Goldene Wärme verbindet sich mit floraler Eleganz und spiritueller Tiefe.',
		'beschreibung_en' => 'Golden warmth blends with floral elegance and spiritual depth.',
		'beschreibung_ar' => 'دفء ذهبي يمتزج مع أناقة زهرية وعمق روحي.',
		'geschlecht' => array(
			'damen',
			'unisex',
		),
		'jahreszeit' => array(
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'blumig',
			'holzig',
			'gourmand',
		),
		'duftnoten' => array(
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'gewuerznoten',
			'harze_balsame',
			'suesse_gourmand',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/820/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/820.png',
		'priority_order' => 74,
	),
	array(
		'id' => 'sy-list-825',
		'name' => 'Duft Nr. 825',
		'name_en' => 'Fragrance No. 825',
		'name_ar' => 'عطر رقم 825',
		'beschreibung' => 'Verspielte Süße verschmilzt mit cremiger Wärme und zarter Sinnlichkeit.',
		'beschreibung_en' => 'Playful sweetness melts into creamy warmth and delicate sensuality.',
		'beschreibung_ar' => 'حلاوة مرحة تذوب في دفء كريمي وحسية رقيقة.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'ausgehen',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 1,
		'alter' => array(
			'20_30',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'fruchtig',
			'gourmand',
			'moschus',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'suesse_gourmand',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/825/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/825.png',
		'priority_order' => 75,
	),
	array(
		'id' => 'sy-list-828',
		'name' => 'Duft Nr. 828',
		'name_en' => 'Fragrance No. 828',
		'name_ar' => 'عطر رقم 828',
		'beschreibung' => 'Fruchtige Leichtigkeit verbindet sich mit floraler Sinnlichkeit und sanfter Wärme.',
		'beschreibung_en' => 'Fruity lightness blends with floral sensuality and gentle warmth.',
		'beschreibung_ar' => 'خفة فاكهية تمتزج مع حسية زهرية ودفء ناعم.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'sommer',
			'fruehling',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'fruchtig',
			'moschus',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'holznoten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/828/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2025/09/828.png',
		'priority_order' => 76,
	),
	array(
		'id' => 'sy-list-833',
		'name' => 'Duft Nr. 833',
		'name_en' => 'Fragrance No. 833',
		'name_ar' => 'عطر رقم 833',
		'beschreibung' => 'Fruchtige Süße verschmilzt mit cremiger Weichheit und romantischer Eleganz.',
		'beschreibung_en' => 'Fruity sweetness melts into creamy softness and romantic elegance.',
		'beschreibung_ar' => 'حلاوة فاكهية تذوب في نعومة كريمية وأناقة رومانسية.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'10_20',
			'20_30',
			'30_40',
			'ueber_40',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'fruchtig',
			'gourmand',
			'moschus',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'fruchtige_noten',
			'harze_balsame',
			'suesse_gourmand',
			'aromatische_noten',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/833/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2026/03/833.webp',
		'priority_order' => 77,
	),
	array(
		'id' => 'sy-list-834',
		'name' => 'Duft Nr. 834',
		'name_en' => 'Fragrance No. 834',
		'name_ar' => 'عطر رقم 834',
		'beschreibung' => 'Zarte Süße verbindet sich mit strahlender Frische und sanfter Wärme.',
		'beschreibung_en' => 'Delicate sweetness blends with radiant freshness and gentle warmth.',
		'beschreibung_ar' => 'حلاوة رقيقة تمتزج مع انتعاش مشرق ودفء ناعم.',
		'geschlecht' => array(
			'damen',
		),
		'jahreszeit' => array(
			'sommer',
			'winter',
			'fruehling',
			'herbst',
		),
		'verwendungsbereich' => array(
			'zuhause',
			'ausgehen',
			'buero',
			'grosse_raeume',
			'meeting',
			'date',
			'private_anlaesse',
		),
		'raucher_geeignet' => 0,
		'alter' => array(
			'10_20',
			'20_30',
		),
		'duftrichtungen' => array(
			'zitrisch',
			'blumig',
			'gourmand',
			'moschus',
		),
		'duftnoten' => array(
			'zitrusnoten',
			'blumige_noten',
			'suesse_gourmand',
			'animalische_noten',
		),
		'produktlink' => 'https://alowidat.de/product/834/',
		'bild' => 'https://alowidat.de/wp-content/uploads/2026/03/834.webp',
		'priority_order' => 78,
	),
);
